"""empty message

Revision ID: cdafccb976a4
Revises: 15a708016a48
Create Date: 2021-09-29 14:01:06.795847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdafccb976a4'
down_revision = '15a708016a48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('feedback', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotels', 'feedback')
    # ### end Alembic commands ###
